#ifndef NITROKEY_PRO_FIRMWARE_MEMORY_LAYOUT_H
#define NITROKEY_PRO_FIRMWARE_MEMORY_LAYOUT_H


// #define FLASH_PAGE_SIZE 512 // AVR
#define FLASH_PAGE_SIZE 1024    // stm32f10x
#define FLASH_START             (0x8000000)

#define GET_FLASH_KB_ADDRESS(x)   (1024*(x)+FLASH_START)

// With bootloader firmware is reaching 80th kB of flash memory.
// Lets start data at 100kB+, so the firmware could grow
#define FLASH_MEMORY_BEGIN        GET_FLASH_KB_ADDRESS(111)
//Lowest region in use found in the firmware - PWS - 112 kB
#define FLASH_MEMORY_LOWEST       GET_FLASH_KB_ADDRESS(112)

#define PWS_FLASH_START_ADDRESS   GET_FLASH_KB_ADDRESS(112)
#define FLASHC_USER_PAGE          GET_FLASH_KB_ADDRESS(119) // 0x801dc00


#define TIME_ADDRESS              GET_FLASH_KB_ADDRESS(121)
#define SLOTS_PAGE1_ADDRESS       GET_FLASH_KB_ADDRESS(122)
#define SLOTS_PAGE2_ADDRESS       GET_FLASH_KB_ADDRESS(123)
#define SLOT1_COUNTER_ADDRESS     GET_FLASH_KB_ADDRESS(124)
#define SLOT2_COUNTER_ADDRESS     GET_FLASH_KB_ADDRESS(125)
#define SLOT3_COUNTER_ADDRESS     GET_FLASH_KB_ADDRESS(126)
#define SLOT4_COUNTER_ADDRESS     GET_FLASH_KB_ADDRESS(111)
#define BACKUP_PAGE_ADDRESS       GET_FLASH_KB_ADDRESS(127)

//Flash size is 128kB, which defines as:
//#define FLASH_MEMORY_LIMIT      GET_FLASH_KB_ADDRESS(128)
#define FLASH_MEMORY_LIMIT 0x8020000


#endif //NITROKEY_PRO_FIRMWARE_MEMORY_LAYOUT_H
